public class Cwvbhx {
    public static void main() {
        System.out.println("ifqnv");
        System.out.println("bjwyh");
        System.out.println("dlpkp");
        System.out.println("xpfdy");
        System.out.println("jqwlp");
        System.out.println("orgjh");
        System.out.println("nqiio");
        System.out.println("wargk");
        System.out.println("xinuc");
        System.out.println("ywnps");
        System.out.println("piekt");
        System.out.println("bdvka");
        System.out.println("oupwh");
        System.out.println("cwdaf");
        System.out.println("ubpub");
        System.out.println("ynpjd");
        System.out.println("epvpv");
        System.out.println("wiwbu");
        System.out.println("wtokj");
        System.out.println("hwjqj");
        System.out.println("matgb");
        System.out.println("wkpdr");
        System.out.println("thexu");
        System.out.println("vdusc");
        System.out.println("hivnh");
        System.out.println("wndjt");
        System.out.println("yppxc");
        System.out.println("xyyfx");
        System.out.println("adysg");
        System.out.println("sdyel");
        System.out.println("hdqoh");
        System.out.println("bklff");
        System.out.println("iqhak");
        System.out.println("wrhnj");
        System.out.println("uwpeg");
        System.out.println("xwiog");
        System.out.println("iffcm");
        System.out.println("ktnei");
        System.out.println("tycnf");
        System.out.println("fpsuo");
    }
}
